### ISSUE TITLE
单击持仓tabPage的时候异常，ret.Code返回null，是因为我没有华泰的账户的原因吗？已经安装了华泰的控件。

### ISSUE THREAD

**Issue by majinke** [qiujoe/StockTrader#10]
public TraderResult GetTradingAccountInfo()
        {
            TraderResult ret = internalGetTradingAccountInfo();//ret.Code返回null
            switch (ret.Code)
            {
                case TraderResultEnum.TIMEOUT:
                    return GetTradingAccountInfo();
                case TraderResultEnum.UNLOGIN:
                    Login();
                    return GetTradingAccountInfo();
                case TraderResultEnum.ERROR:
                case TraderResultEnum.SUCCESS:
                    return ret;
                default:
                    return null;
            }
        }

        protected virtual TraderResult internalGetTradingAccountInfo()
        {
            return null;
        }

>	Stock.Common.dll!Stock.Trader.BaseStockTrader.GetTradingAccountInfo() 行 170	C#
 	StockTrader.exe!Stock.Account.XiaDan.GetCashInfo() 行 177 + 0xc 字节	C#
 	StockTrader.exe!StockTrader.Form1.GetStockPosition() 行 390 + 0x10 字节	C#
 	StockTrader.exe!StockTrader.Form1.tabControl1_SelectedIndexChanged(object sender, System.EventArgs e) 行 369 + 0x8 字节	C#
 	[外部代码]	
 	StockTrader.exe!StockTrader.Program.Main() 行 48 + 0x1d 字节	C#
 	[外部代码]

**Comment by kiss2keys** [comment]
请问华泰的控件怎么安装，我把Lib下边的Interop.CSSWEBLOGINHTLib.dll,AxInterop.CSSWEBLOGINHTLib.dll 
添加引用后，打开华泰窗体报“没有注册类 (异常来自 HRESULT:0x80040154 ” 是不是还要注册什么OCX呢？求解，非常感谢

**Comment by majinke** [comment]
大致情况是这样：到华泰官方网站，找web交易，会自动要求你下载华泰的安全控件，文件名是htnet_client.exe

**Comment by qiujoe** [comment]
这个问题不明，无法再现

**Comment by kiss2keys** [comment]
你把配置修改为华泰了吗？把下边的注释打开，上边的注释掉。华泰好像支持3种接口，有web的，那两种具体是什么？目测应该是桌面程序的吧，正在研究
  <CurrentStock name="Mock证券接口" dll="Stock.Common.dll" clazz="Stock.Trader.MockStockTrader"/>
  <CurrentMarketListener name="Sina" dll="Stock.Market.Sina.dll" clazz="Stock.Market.Sina.SinaStockMarketListener"/>

**Comment by dyverin** [comment]
这个问题应该是Stock.Trader.Gui\app.config 中CurrentStock 没有配成Stock.Trader.HuaTai.dll. 因为Stock.Trader.Ths.dll是楼主私有的。

**Comment by majinke** [comment]
我这里配置了以后也不行------------------------------------------------------------------发件人：dyverin <notifications@github.com>发送时间：2015年12月2日(星期三) 21:28收件人：qiujoe/StockTrader <StockTrader@noreply.github.com>抄　送：cc330 <cc330@aliyun.com>主　题：Re: [StockTrader] 单击持仓tabPage的时候异常，ret.Code返回null，是因为我没有华泰的账户的原因吗？已经安装了华泰的控件。 (#10)这个问题应该是Stock.Trader.Gui\app.config 中CurrentStock 没有配成Stock.Trader.HuaTai.dll. 因为Stock.Trader.Ths.dll是楼主私有的。

**Comment by qiujoe** [comment]
请去群论坛里看最新的如何遍野和证券运行
