### ISSUE TITLE
stock.db3文件损坏

### ISSUE THREAD

**Issue by ismlsmile** [qiujoe/StockTrader#11]
代码库中的该文件貌似无法用常规的sqlite编辑文件打开

**Comment by qiujoe** [comment]
无问题，误报

**Comment by ismlsmile** [comment]
原因我知道了，StockTrader目录下的stock.db3是坏的，我拷的是这个，StockTrader\Stock.Trader.Gui目录下的stock.db3文件是好的，感觉把StockTrader下的这个文件删了吧，容易误导。
