### ISSUE TITLE
请问Mock证券接口是指的同花顺统一委托登录这个程序吗？

### ISSUE THREAD

**Issue by kiss2keys** [qiujoe/StockTrader#16]
如果不是，那是什么呢？需要运行哪个程序才能正常使用？支持哪些券商?谢谢
还有 华泰的 3个接口 除了web接口另外两个是哪个程序的接口？应该有 华泰证券(专业版Ⅱ交易)吧？
问题有点多，非常感谢！

**Comment by qiujoe** [comment]
不是， mock 是模拟接口
其他接口看拼音的名字
ths 同花顺
tdx 通达信
