### ISSUE TITLE
编译时候说找不到AxCSSWEBLOGINHTLib，这是什么

### ISSUE THREAD

**Issue by larryxin** [qiujoe/StockTrader#17]
在编译Stock.Trader.HuaTai 这个项目的时候说有个错误。
错误	6	未能找到类型或命名空间名称“AxCSSWEBLOGINHTLib”(是否缺少 using 指令或程序集引用?)	25\StockTrader-master\Stock.Trader.HuaTai\FormInputValidateCode.Designer.cs	63	34	Stock.Trader.HuaTai
这是什么组件，有用不。。
还有个运行时错误，是NullReferenceException 在运行GUI的时候发生的，出错点在
StockCommon里面的SqliteHelper.cs里的138行
 if(session == null）
                session = factory.OpenSession();
好像factory没有初始化

**Comment by larryxin** [comment]
刚装了一下华泰的密码组件，编译通过了，AxCSSWEBLOGINHTLib应该是华泰密码组件
好像还要点一下才行。。
但是NullReferenceException 还是会有，原因未知

**Comment by dyverin** [comment]
我也遇到“AxCSSWEBLOGINHTLib” 这个问题，请问你安装的是哪个密码组件？我在华泰官网上没有找到。谢谢。

**Comment by hgxxx007** [comment]
CSSWEBLOGINHT.dll是华泰网上营业厅的登录插件，AxCSSWEBLOGINHTLib是前面的dll转换而来的，在git根目录的lib目录下面。如果担心安全问题，可以自行去华泰网厅安装插件后，在本地c盘找到CSSWEBLOGINHT.dll后，自行转换。
