### ISSUE TITLE
“System.TypeInitializationException”类型的未经处理的异常在 StockTrader.exe 中发生   其他信息: “Stock.Account.XiaDan”的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by pollysu** [qiujoe/StockTrader#19]
“System.TypeInitializationException”类型的未经处理的异常在 StockTrader.exe 中发生 

其他信息: “Stock.Account.XiaDan”的类型初始值设定项引发异常。

运行时报错，请教下怎么解决，谢谢

**Comment by qiujoe** [comment]
请去群论坛里看最新的如何编译和正确运行
