### ISSUE TITLE
有无打算加入新浪L2接口？

### ISSUE THREAD

**Issue by xposlosq** [qiujoe/StockTrader#2]
新浪L2接口走的websocket协议，对行情毫秒级的延迟。

http://finance.sina.com.cn/realstock/company/sz002069/l2.shtml

0.登录新浪，并且有L2普及版权限

1.取得token, get方式。https://current.sina.com.cn/auth/api/jsonp.php/getToken/AuthSign_Service.getSignCode?query=hq_pjb&ip=" + ip + stockGetUrl 

2.连接行情, ws方式
 new WebSocket('ws://ff.sinajs.cn/wskt?token=' + token + stockGetUrl);

其中stockGetUrl为所请求数据的内容
如："2cn_"+stock.stockCode+",2cn_"+stock.stockCode+"_orders,2cn_"+stock.stockCode+"_0,2cn_"+stock.stockCode+"_1,"+stock.stockCode+"_i

**Comment by qiujoe** [comment]
非常感谢，你提供的资料。暂时没有开源计划支持L2。

**Comment by qiujoe** [comment]
L2只打算几个好朋友之间来分享，如果你有意，可以联系我的QQ
