### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by yinhm** [qiujoe/StockTrader#5]
*  有两处 using Stock.Trader.Settings 应该是 Stock.Account.Settings ?
 * 一堆接口未实现？

估计是您的项目还在迅速改动之中，能不能发一个较稳定的版本呢？方便入手，谢谢。

**Comment by aalennku** [comment]
我也搞不过，学c#以及看代码中。。。。

**Comment by qiujoe** [comment]
我尽快重构结束

**Comment by qiujoe** [comment]
已经重构结束
