### ISSUE TITLE
编译失败：未能找到引用的组件“System.Data.SQLite.Linq“，不实现接口成员

### ISSUE THREAD

**Issue by majinke** [qiujoe/StockTrader#7]
编译过程中，报错：
未能找到引用的组件“System.Data.SQLite.Linq“

不实现接口：错误1	“Stock.Trader.BaseStockTrader”不实现接口成员“Stock.Trader.IStockTrader.GetTodayEntrustList()”	D:\StockTrader-master\Stock.Common\Trader\BaseStockTrader.cs	32	27	Stock.Common

错误	2	“Stock.Trader.BaseStockTrader”不实现接口成员“Stock.Trader.IStockTrader.CancelStock(int)”	D:\StockTrader-master\Stock.Common\Trader\BaseStockTrader.cs	32	27	Stock.Common

错误	3	“Stock.Strategy.BaseStrategy”不实现接口成员“Stock.Trader.IStockTrader.GetTodayEntrustList()”	D:\StockTrader-master\Stock.Common\Strategy\BaseStrategy.cs	42	27	Stock.Common

错误	4	“Stock.Strategy.BaseStrategy”不实现接口成员“Stock.Trader.IStockTrader.CancelStock(int)”	D:\StockTrader-master\Stock.Common\Strategy\BaseStrategy.cs	42	27	Stock.Common

错误	5	“Stock.Strategy.BaseStrategy”不实现接口成员“Stock.Strategy.IStrategy.Enabled”	D:\StockTrader-master\Stock.Common\Strategy\BaseStrategy.cs	42	27	Stock.Common

错误	6	“Stock.Strategy.BaseStrategy”不实现接口成员“Stock.Strategy.IStrategy.Id”	D:\StockTrader-master\Stock.Common\Strategy\BaseStrategy.cs	42	27	Stock.Common

**Comment by qiujoe** [comment]
已修改，thx
