### ISSUE TITLE
运行时异常

### ISSUE THREAD

**Issue by majinke** [qiujoe/StockTrader#9]
在 System.NullReferenceException 中第一次偶然出现的“Stock.Common.dll”类型的异常
   在 NHibernate.Cfg.ConfigurationSchema.HibernateConfiguration..ctor(XmlReader hbConfigurationReader, Boolean fromAppSetting)
   在 NHibernate.Cfg.ConfigurationSchema.HibernateConfiguration..ctor(XmlReader hbConfigurationReader)
   在 NHibernate.Cfg.Configuration.Configure(XmlReader textReader)
   在 NHibernate.Cfg.Configuration.Configure(String fileName, Boolean ignoreSessionFactoryConfig)
   在 NHibernate.Cfg.Configuration.Configure(String fileName)
   在 NHibernate.Cfg.Configuration.Configure()
   在 Stock.Local.SqlLite.Hibernate.SqliteHelper..ctor() 位置 D:\GitHub\StockTrader\Stock.Common\Sqlite\SqliteHelper.cs:行号 55

已经将EntrustRecord.hbm.xml、hibernate.cfg.xml、StockHolder.hbm.xml、StrategyDesc.hbm.xml、SubTradingAccount.hbm.xml、TransactionRecord.hbm.xml、XueQiuCube.hbm.xml、stock.db3文件拷贝到运行目录下

**Comment by qiujoe** [comment]
是由于sqlite的 dll 没有复制到 运行目录导致的问题。 
不能自动复制，就手动复制

**Comment by majinke** [comment]
谢谢！------------------------------------------------------------------发件人：qiujoe <notifications@github.com>发送时间：2015年11月20日(星期五) 16:02收件人：qiujoe/StockTrader <StockTrader@noreply.github.com>抄　送：cc330 <cc330@aliyun.com>主　题：Re: [StockTrader] 运行时异常 (#9)
是由于sqlite的 dll 没有复制到 运行目录导致的问题。 

不能自动复制，就手动复制
